### ISSUE TITLE
[bug] Uploading a file from Android does not work

### ISSUE THREAD

**Issue by femo1de** [crocodilestick/Calibre-Web-Automated#166]
**Describe the bug**
When you open CWA on an Android phone and use the upload dialog, it always fails with the message "File to be uploaded must have an extension". The same file uploaded from Windows to CWA via the upload dialog works fine.

**To Reproduce**

1. Open CWA on Android 
2. Click on the Upload Button in the Menu
3. Android will ask you how to choose a file: Camera, Video, Recorder, Media Picker
4. Select Media Picker
5. Select .epub file and confirm
6. File uploads but will later file with the message "File to be uploaded must have an extension"

**Expected behavior**
Uploading via Android / Mobile works

**Comment by crocodilestick** [comment]
Try the dev image, it's possible this is something that was fixed in the latest CW version

**Comment by femo1de** [comment]
Sorry, current dev image (2.2.0-dev_build_37) doesnt change it, the bug is still there

**Comment by crocodilestick** [comment]
I'm sorry but it's likely either a problem with your configuration or with the file you're trying to upload (if you got the file from somewhere like Anna's Archive, it's almost certainly the file). I've tried several times with numerous different files on my android phone and it works exactly as expected. Are you using the chrome app as your browser?

![Screenshot_20250107-114911.jpg](https://github.com/user-attachments/assets/6ca96373-4795-4947-aeaf-e675edacbc4f)

**Comment by femo1de** [comment]
Ok very weird I have tested it again and now can't reproduce the error anymore. I was using Edge on Android and tested it with always the same files, they worked when i uploaded from windows but not from android. 

Since I can't reproduce the issue anymore I'll close this bug. I played around with CWA and restarted the container a few times, maybe one of these things fixed the issue
