### ISSUE TITLE
[bug] CWA library fails to find files that it's trying to convert

### ISSUE THREAD

**Issue by Waggleworx** [crocodilestick/Calibre-Web-Automated#219]
**Describe the bug**
My large library fails kobo syncs sometimes if files aren't already converted to kepub.  I decided to try using CWA Library Convertor after temporarily changing the target format from epub to kepub.  After completion, I did NOT find new kepub formats for all of my books

**To Reproduce**
1. Ingest epub books with epub as default
2. change target format to kepub
3. run convertor
4. check books that didn't have kepub

**Expected behavior**
I'd expect kepub for all books to be available

**Screenshots**
CWA log contains a lot of this for every file.  It looks like the path to move the starting file might not be constructed correctly since it can't find the file

```
[convert-library]: ERROR - The following error occurred when trying to copy Headhunted to Another World - From Salarym - Benigashira.epub to /config/processed_books/converted:
[Errno 2] No such file or directory: 'Headhunted to Another World - From Salarym - Benigashira.epub'
[convert-library]: (120/251) Intermediate conversion of Headhunted to Another World - From Salarym - Benigashira.epub to epub from .epub successful, now converting to kepub...
[convert-library]: ERROR - The following error occurred when trying to copy Headhunted to Another World - From Salarym - Benigashira.epub to /config/processed_books/converted:
[Errno 2] No such file or directory: 'Headhunted to Another World - From Salarym - Benigashira.epub'
[convert-library]: ERROR - The following error occurred when trying to copy /config/.cwa_conversion_tmp/Headhunted to Another World - From Salarym - Benigashira.kepub to /config/processed_books/imported:
[Errno 2] No such file or directory: '/config/.cwa_conversion_tmp/Headhunted to Another World - From Salarym - Benigashira.kepub'
[convert-library]: (120/251) Import of Headhunted to Another World - From Salarym - Benigashira.kepub successfully completed!
[convert-library]: (120/251) Successfully set ownership of new files in /calibre-library/ to abc:abc.
[convert-library]: (121/251) Converting Headhunted to Another World - From Salarym - Benigashira.epub from .epub format to kepub format...
```

**Configuration(please complete the following information):**
 - OS: Docker container
 - Hardware: Synology NAS
 - Version 3.0.1

**Additional context**
n/a

**Comment by avephill** [comment]
experiencing this too on version 3.0.1 on docker container

**Comment by crocodilestick** [comment]
Fixed as of V3.0.2

**Comment by ajoliveau** [comment]
I actually have the same issue. I'm on crocodilestick/calibre-web-automated:latest (so 3.0.4) I guess ? Just installed it this afternoon.
docker-compose.yml : 
```
version: '3'

services:
  calibre-web-automated:
    image: crocodilestick/calibre-web-automated:latest
    container_name: calibre-web-automated
    environment:
      # Only change these if you know what you're doing
      - PUID=1000
      - PGID=1000
      - TZ=UTC 
    volumes:
      - ./config:/config 
      - ./books:/calibre-library 
    ports:
      - 8083:8083 
    restart: unless-stopped
    networks:
      - web

  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
    networks:
      - web

networks:
  web:
    driver: bridge
```

Every book has this in the log : 
```
[convert-library]: (50/89) *** NOTICE TO USER: Kepubify is limited in that it can only convert from epubs. To get around this, CWA will automatically convert other supported formats to epub using the Calibre's conversion tools & then use Kepubify to produce your desired kepubs. Obviously multi-step conversions aren't ideal so if you notice issues with your converted files, bare in mind starting with epubs will ensure the best possible results***

[convert-library]: ERROR - The following error occurred when trying to copy La vraie vie - Adeline Dieudonne.epub to /config/processed_books/converted:
[Errno 2] No such file or directory: 'La vraie vie - Adeline Dieudonne.epub'
[convert-library]: (50/89) Intermediate conversion of La vraie vie - Adeline Dieudonne.epub to epub from .epub successful, now converting to kepub...
[convert-library]: ERROR - The following error occurred when trying to copy La vraie vie - Adeline Dieudonne.epub to /config/processed_books/converted:
[Errno 2] No such file or directory: 'La vraie vie - Adeline Dieudonne.epub'
[convert-library]: ERROR - The following error occurred when trying to copy /config/.cwa_conversion_tmp/La vraie vie - Adeline Dieudonne.kepub to /config/processed_books/imported:
[Errno 2] No such file or directory: '/config/.cwa_conversion_tmp/La vraie vie - Adeline Dieudonne.kepub'
[convert-library]: (50/89) Import of La vraie vie - Adeline Dieudonne.kepub successfully completed!
[convert-library]: (50/89) Successfully set ownership of new files in /calibre-library/ to abc:abc.
```

/config/.cwa_conversion_tmp exists, I tried to run `docker exec -it calibre-web-automated /bin/bash` and permissions are ok, I can write files in all the folders.
Library in calibre-web is set to /calibre-library, and ~/books is my Calibre library that I rsynced. Everything work, but the conversion :/

**Comment by ajoliveau** [comment]
Any update on this ? I installed a new CWA instance on Unraid

```
<h2>Version Information 📜</h2>
      
Distribution | Version | Détails
-- | -- | --
Calibre-Web Automated | V3.0.4 | Version actuelle
Stock Calibre-Web | 0.6.24 | Version actuelle
Linuxserver.io | 0.6.24-ls304 | Version actuelle
Calibre | 7.16.0 | -
Kepubify | v4.0.4
```

Still the same error. Is it a problem with my library format ?

Uploading, downloading, and manually converting single files work. Only the CWA Library Convertor fails

**Comment by Dee76** [comment]
I'm experiencing the same issue. The folders and log file mentioned in #223 already existed. Testing via terminal shows that permissions don't seem to be a problem (files can be created, ownership changed, etc.). I noticed this with CWA v3.0.4. I also rebuilt using v3.0.1 and the behaviour is identical.

Purely a guess, but is some of the file conversion logic dropping the path to the original file in the library? I only ask since the full path isn't shown in the log for the original file, but then is logged for the expected `/config/.cwa_conversion_tmp` converted file.

**Comment by Dee76** [comment]
I've submitted PR #371 with a fix to this issue in the `convert_library.py` script. I've tested it and deployed it in my environment. Kepub conversion is working again with this fix.

@crocodilestick apology for the tag, but I don't want the fix to get lost due to a closed issue. Thanks!
