### ISSUE TITLE
[bug] Bulk edit mark selected books as read/unread doesn't work

### ISSUE THREAD

**Issue by ljo123** [crocodilestick/Calibre-Web-Automated#222]
In books list I select multiple books and then use the "Mark Selected Books as Read" button at the top and nothing happens

**To Reproduce**
1. Go to books list
2. Click on multiple books with the left hand checkbox
3. Click the Mark Selected as Read

Books should be marked as read

**Configuration(please complete the following information):**
 - OS: Ubuntu 24.04
 - Browser: Firefox latest
 - CWA: latest

**Comment by Tooelite** [comment]
The same error seems to appear for fields like publisher for example.

There is a 405 error on the browser console: "Method not allowed"

**Comment by mateuszzadorski** [comment]
Same issue with deleting, in my case on Docker.

**Comment by Domoel** [comment]
The bulk edit feature does not work at all after updating to 3.0.1. Can anybody confirm this?

**Comment by DennaGherlyn** [comment]
I can't use bulk edit as well. I'm also on 3.0.1.

**Comment by crocodilestick** [comment]
Looking into this now

**Comment by crocodilestick** [comment]
Issue Fixed in Version 3.0.4

**Comment by slinky34** [comment]
Hi, 

I'm on the current version of CWA (3.0.4)and still having this issue. I just recently added my app.db from the calibre-web instance, so I wonder if that's related. 

Configuration(please complete the following information):

OS: Ubuntu 24.04
Browser: Chrome Latest
CWA: latest
