### ISSUE TITLE
[bug] Download function has stopped working - 404 error

### ISSUE THREAD

**Issue by DoubtfulTurnip** [crocodilestick/Calibre-Web-Automated#281]
I noticed recently that the download function has stopped working. I rolled my server back to version 2.1.2 and everything works as expected again.

Here are the details for my container when I restore my entire server back to a previous restore point.

```
Distribution 	Version 	Details
Calibre-Web Automated 	V2.1.2 	Current Version
Stock Calibre-Web 	0.6.23 	Current Version
Linuxserver.io 	0.6.23-ls291 	Current Version
Calibre 	v7.26.0 	-
Kepubify 	v4.0.4 	-

[2025-02-27 15:34:44,137]  INFO {cps:166} *** "requests" version does not meet the requirements. Should: <2.32.0, Found: 2.32.3, please consider installing required version ***
[2025-02-27 15:34:44,137]  INFO {cps:175} Starting Calibre Web...
[2025-02-27 15:34:45,091]  WARN {py.warnings:109} /lsiopy/lib/python3.10/site-packages/flask_limiter/extension.py:333: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
  warnings.warn(
[2025-02-27 15:34:45,914]  INFO {apscheduler.scheduler:181} Scheduler started
[2025-02-27 15:34:45,915]  INFO {apscheduler.scheduler:895} Added job "reconnect" to job store "default"
[2025-02-27 15:34:45,915]  INFO {apscheduler.scheduler:895} Added job "delete temp" to job store "default"
[2025-02-27 15:34:45,916]  INFO {apscheduler.scheduler:895} Added job "end scheduled task" to job store "default"
[2025-02-27 15:34:45,916]  INFO {apscheduler.scheduler:895} Added job "immediately delete temp" to job store "default"
[2025-02-27 15:34:45,930]  INFO {apscheduler.executors.default:123} Running job "immediately delete temp (trigger: date[2025-02-27 15:34:45 NZDT], next run at: 2025-02-27 15:34:45 NZDT)" (scheduled at 2025-02-27 15:34:45.916600+13:00)
[2025-02-27 15:34:45,933]  INFO {apscheduler.scheduler:641} Removed job 6efa73d1fef44f8ab6a83668d0196cdd
[2025-02-27 15:34:45,951]  INFO {apscheduler.executors.default:144} Job "immediately delete temp (trigger: date[2025-02-27 15:34:45 NZDT], next run at: 2025-02-27 15:34:45 NZDT)" executed successfully
[2025-02-27 15:34:47,778]  WARN {py.warnings:109} /lsiopy/lib/python3.10/site-packages/pypdf/_crypt_providers/_cryptography.py:32: CryptographyDeprecationWarning: ARC4 has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.ARC4 and will be removed from this module in 48.0.0.
  from cryptography.hazmat.primitives.ciphers.algorithms import AES, ARC4
[2025-02-27 15:34:50,674]  INFO {cps.server:218} Starting Gevent server on [::]:8083
[2025-02-27 15:47:19,662]  INFO {cps.helper:978} Downloading file: /calibre-library/Liu Cixin/The Three-Body Problem (27719)/The Three-Body Problem - Liu Cixin.epub
[2025-02-27 19:05:45,117]  WARN {cps.config_sql:384} Log path  not valid, falling back to default```
```

After adding the tag V3.0.0 to the container instead of using latest (while still on version 2.1.2) and then pull the image I see the following when trying to download a book.

```
Version Information 📜
Distribution 	Version 	Details
Calibre-Web Automated 	V3.0.0 	Current Version
Stock Calibre-Web 	0.6.24 	Current Version
Linuxserver.io 	0.6.24-ls304 	Current Version
Calibre 	v7.26.0 	-
Kepubify 	v4.0.4 	-

[2025-02-27 20:14:53,322]  WARN {py.warnings:109} /lsiopy/lib/python3.10/site-packages/flask_limiter/extension.py:333: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
  warnings.warn(
[2025-02-27 20:14:53,643]  INFO {apscheduler.scheduler:181} Scheduler started
[2025-02-27 20:14:53,644]  INFO {apscheduler.scheduler:895} Added job "reconnect" to job store "default"
[2025-02-27 20:14:53,644]  INFO {apscheduler.scheduler:895} Added job "delete temp" to job store "default"
[2025-02-27 20:14:53,645]  INFO {apscheduler.scheduler:895} Added job "end scheduled task" to job store "default"
[2025-02-27 20:14:53,646]  INFO {apscheduler.scheduler:895} Added job "immediately delete temp" to job store "default"
[2025-02-27 20:14:53,647]  INFO {apscheduler.executors.default:123} Running job "immediately delete temp (trigger: date[2025-02-27 20:14:53 NZDT], next run at: 2025-02-27 20:14:53 NZDT)" (scheduled at 2025-02-27 20:14:53.645883+13:00)
[2025-02-27 20:14:53,648]  INFO {apscheduler.scheduler:641} Removed job e3750a566fd54f32875a65c04b87b6f2
[2025-02-27 20:14:53,657]  INFO {apscheduler.executors.default:144} Job "immediately delete temp (trigger: date[2025-02-27 20:14:53 NZDT], next run at: 2025-02-27 20:14:53 NZDT)" executed successfully
[2025-02-27 20:14:55,875]  INFO {cps.server:218} Starting Gevent server on [::]:8083
[2025-02-27 20:15:47,915] ERROR {cps.embed_helper:45} Metadata embedder encountered an error: Traceback (most recent call last):
  File "runpy.py", line 198, in _run_module_as_main
  File "runpy.py", line 88, in _run_code
  File "site.py", line 47, in <module>
  File "site.py", line 43, in main
  File "calibre/db/cli/main.py", line 253, in main
  File "calibre/db/cli/main.py", line 40, in run_cmd
  File "calibre/db/cli/cmd_export.py", line 168, in main
  File "calibre/db/cli/cmd_export.py", line 143, in export
  File "calibre/db/cli/main.py", line 184, in run
  File "calibre/db/cli/main.py", line 171, in db
  File "calibre/db/legacy.py", line 191, in __init__
  File "calibre/db/legacy.py", line 46, in create_backend
  File "calibre/db/backend.py", line 489, in __init__
  File "calibre/utils/filenames.py", line 128, in is_case_sensitive
PermissionError: [Errno 13] Permission denied: '/calibre-library/calibre_test_case_sensitivity.txt'
```

I also tried removing the dockermod line in my compose file

```
      #- DOCKER_MODS=linuxserver/mods:universal-calibre
```

After deploying again I have the following versions

```
Version Information 📜
Distribution 	Version 	Details
Calibre-Web Automated 	V3.0.0 	Current Version
Stock Calibre-Web 	0.6.24 	Current Version
Linuxserver.io 	0.6.24-ls304 	Current Version
Calibre 	7.16.0 	-
Kepubify 	v4.0.4 	-
```

The download function still does not work.

Filesystem changes to permissions have not taken place between versions, so I am unsure what is causing the issue.

When clicking on a download option for a book I receive a 404 error.

I am, however, able to read the book within the web interface.

The books are located on a Synology NAS and are linked to the Ubuntu server via SMB. I have not had any issues in the past with downloading books via Calibre-Web-Automated

**Comment by Na3blis** [comment]
I'm trying to send to kindle and I'm also seeing a similar error:
```
[2025-02-28 20:51:35,919] ERROR {cps.embed_helper:45} Metadata embedder encountered an error: Traceback (most recent call last):
  File "runpy.py", line 198, in _run_module_as_main
  File "runpy.py", line 88, in _run_code
  File "site.py", line 47, in <module>
  File "site.py", line 43, in main
  File "calibre/db/cli/main.py", line 253, in main
  File "calibre/db/cli/main.py", line 40, in run_cmd
  File "calibre/db/cli/cmd_export.py", line 168, in main
  File "calibre/db/cli/cmd_export.py", line 149, in export
  File "calibre/library/save_to_disk.py", line 344, in do_save_book_to_disk
PermissionError: [Errno 13] Permission denied: '/tmp/calibre_web/21ed83f4-d36b-40ed-b94b-fc477f4a4f30.jpg'
[2025-02-28 20:51:35,920] ERROR {cps.tasks.mail:148} [Errno 2] No such file or directory: '/tmp/calibre_web/21ed83f4-d36b-40ed-b94b-fc477f4a4f30.epub'
[2025-02-28 20:51:35,920] ERROR {cps.tasks.mail:273} The requested file could not be read. Maybe wrong permissions?
```

```
Calibre-Web Automated	V3.0.4	Current Version
Stock Calibre-Web	0.6.24	Current Version
Linuxserver.io	0.6.24-ls304	Current Version
Calibre	v7.16.0	-
Kepubify	v4.0.4	-
```

**Comment by Na3blis** [comment]
For me at least, this appears to be an issue when I do things in calibre directly instead of in CWA. The only way I've been able to fix it is to change the version of my docker container so it rebuilds it, then I can switch back. Was able to do this multiple times. Modified something in calibre, switched version to 3.0.3, downloads started working again. Modified another thing, downloads broke (though opening the book still works), then switched version back to 3.0.4 and CWA was once again back to working

**Comment by LondonDragon** [comment]
Hi everyone,
Is there a fix for this?
Thanks

**Comment by FennyFatal** [comment]
(For me) This appears to be due to old kernel version on my docker host (synology)

I was able to work around it by doing the following in the docker container:
```
apt-get install binutils
strip --remove-section=.note.ABI-tag /app/calibre/lib/libQt6*
```

**Comment by DoubtfulTurnip** [comment]
> (For me) This appears to be due to old kernel version on my docker host (synology)
> 
> I was able to work around it by doing the following in the docker container:
> 
> apt-get install binutils
> strip --remove-section=.note.ABI-tag /app/calibre/lib/libQt6*
> 
> _EDIT_ Dropping the following file in /custom-cont-init.d via a volume mount worked a treat.
> 
>   volumes:
>       - /configs/calibre-web-automated/custom_files:/custom-cont-init.d:ro
> 
> [fix_calibre_qt6.sh.txt](https://github.com/user-attachments/files/19290057/fix_calibre_qt6.sh.txt)

I have tried this but unfortunately this did not work in my case. After updating the docker image, I am still unable to download books due to a 404 error.

**Comment by DoubtfulTurnip** [comment]
As a further test I completely deleted my config folder for the container on my Ubuntu server, removed the latest image in Docker (V3.0.4) and started fresh. When using the latest image, I am having the same issue. 

This looks as though there might be an issue within the Calibre part of the image that is causing my issue.

Any assistance would be helpful, otherwise I will just have to pin the tag V2.1.2 for the foreseeable future

**Comment by crocodilestick** [comment]
Fixed as of V3.1.0 ❤️

**Comment by berlincount** [comment]
I still get this problem in the DEV version; it's related to embedding metadata in the downloaded file - it tries to write a file into my (write-protected) library folder to check whether the filesyste is case sensitive .. while this edit would be done in the /tmp folder.

**Comment by j8ith** [comment]
I have the same issue as others on v4.0.6.  I also have a Read only /calibre-library folder mounted. The error that occurs along with the 404 in the container logs is: 

[calibre-web-automated] 2026-02-19T21:56:36.493549050Z OSError: [Errno 30] Read-only file system: '/calibre-library/calibre_test_case_sensitivity.txt'
[calibre-web-automated] 2026-02-19T21:56:36.493549762Z 
[calibre-web-automated] 2026-02-19T21:56:36.493550417Z [2026-02-19 16:56:36,493]  WARN {cps.embed_helper:61} No file named ca5455e6-9493-475e-976f-0d4dd0466f04.epub found in /tmp/calibre_web

Apologies, noticed this was closed as a previous issue... I will open a new bug report for this.
