### ISSUE TITLE
[bug] Refresh Library Command Does Not Update With New Books

### ISSUE THREAD

**Issue by strangedesign13** [crocodilestick/Calibre-Web-Automated#287]
**Describe the bug**
Using the Refresh Library GUI command results in a notification that the library has been refreshed, but no new books are shown, I need to reboot the container to get a refresh to occur.

**To Reproduce**
1. Go to 'Main Page'
2. Click on 'Refresh Library'
3. See 'Library Refresh 🔄 - Library refreshed & ingest process complete! ✅'
4. No new books appear 

**Expected behavior**
New books should appear in the GUI

**Screenshots**

**Configuration(please complete the following information):**
 - OS: [Debian]
 - Hardware: [Proxmo LXC with Docker]
 - Version V3.0.4

**Comment by hjdarnel** [comment]
I have the same. Occasionally it will work on a docker-compose restart. Docker compose entry:
```yaml
version: '3'
services:
  calibre-web-automated:
    image: crocodilestick/calibre-web-automated:latest
    container_name: calibre
    environment:
      # Only change these if you know what you're doing
      - PUID=1000
      - PGID=1000
      # Edit to match your current timezone https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - TZ=America/Chicago 
    volumes:
      - ./calibre-web-automated/config:/config 
      - ./calibre-web-automated/books:/calibre-library 
      # This is an ingest dir, NOT a library one. Anything added here will be automatically added to your library according to the settings you have configured in CWA Settings page.
      # All files placed here are REMOVED AFTER PROCESSING :(
      -  /mnt/c/Watched/Calibre/:/cwa-book-ingest
    ports:
      - 8083:8083 
    restart: unless-stopped
```

**Comment by yossile** [comment]
Also experiencing this. I have a library in a syncthing receive-only and when I add books I hit refresh in the GUI but no new books are added.
They do show up after I restart the container.

**Comment by jonskoglund** [comment]
Yes I can confirm that a restart of the container will add the missing books. Did a lot of troubleshooting to end up with the workaround @hjdarnel mentioned. Maybe for now a cron job that triggers a container restart every x hours can be a temporary solution until this issue is fixed.

**Comment by crocodilestick** [comment]
Fixed in v4.0.0

**Comment by elmpp** [comment]
I still see this behaviour now (dev-382 docker branch - required due to the 4.0.1 breakage). Restarting the container does not seem to help. 

(Synology, V4.0.2, Docker-compose)

```
calibre-web-automated:
    image: crocodilestick/calibre-web-automated:v4.0.2 # due to oauth support through - https://github.com/crocodilestick/Calibre-Web-Automated/releases/tag/v4.0.1
    #image: crocodilestick/calibre-web-automated:dev-382 # dev due to https://github.com/crocodilestick/Calibre-Web-Automated/issues/950#issuecomment-3825042086
    container_name: calibre-web-automated
    environment:
      # PUID=1028
      - PGID=65536
      - TZ=Europe/Amsterdam
      - UMASK=022
      # Hardcover API Key required for Hardcover as a Metadata Provider, get one here: https://docs.hardcover.app/api/getting-started/
      - HARDCOVER_TOKEN='Bearer wefwefw'
      # If your library is on a network share (e.g., NFS/SMB), disable WAL to reduce locking issues
      # Accepts: true/false (default: false)
      #- NETWORK_SHARE_MODE=false
      # Override the default port (8083) for the web server.
      # Accepts any valid port number.
      - CWA_PORT_OVERRIDE=8083
    volumes:
      # CW users migrating should stop their existing CW instance, make a copy of the config folder, and bind that here to carry over all of their user settings ect.
      - /volume2/docker/projects/calibre-web-automator/config:/config
      # This is an ingest dir, NOT a library one. Anything added here will be automatically added to your library according to the settings you have configured in CWA Settings page. All files placed here are REMOVED AFTER PROCESSING
      - /volume1/data/media-arr/ebooks-manual:/cwa-book-ingest
      # If you don't have an existing library, CWA will automatically create one at the bind provided here
      - /volume1/data/media-arr/ebooks/calibre:/calibre-library
      # If you use calibre plugins, you can bind your plugins folder here to have CWA attempt to add them to its workflow (WIP)
      # If you are starting with a fresh install, you also need to copy customize.py.json to the Calibre config volume above, in /path/to/config/folder/.config/calibre/customize.py.json, see the note below for more info
      # - /path/to/your/calibre/plugins/folder:/config/.config/calibre/plugins
    ports:
      # Change the first number to change the port you want to access the Web UI, not the second
      - 8083:8083
    # If you set CWA_PORT_OVERRIDE to a port below 1024, you may need to uncomment the following line:
    # cap_add:
    #   - NET_BIND_SERVICE
    restart: unless-stopped
```
