### ISSUE TITLE
[bug] Authors interface has display bugs

### ISSUE THREAD

**Issue by turkeyphant** [crocodilestick/Calibre-Web-Automated#298]
**Describe the bug**
Authors interface has display bugs

**To Reproduce**
1. Go to authors
2. There is a white bust overlapping all the characters and the word "Authors" also seems to be in the wrong place

**Expected behavior**
No overlapping content

**Screenshots**

![Image](https://github.com/user-attachments/assets/9b29d27f-fa39-4755-be86-99ce7a73859d)

Configuration(please complete the following information):

OS: Unraid
Hardware: i3 12100 • 32 GB DDR4 • Z690
Calibre-Web Automated | V3.0.4 | Current Version
Stock Calibre-Web | 0.6.24 | Current Version
Linuxserver.io | 0.6.24-ls304 | Current Version
Calibre | 7.16.0 | -
Kepubify | v4.0.4 | -
Additional context

**Comment by crocodilestick** [comment]
Ah, this element was styled with only the Latin alphabet in mind, I'll work on a fix 😅

**Comment by crocodilestick** [comment]
Fixed in next dev, will be in next release

**Comment by turkeyphant** [comment]
Afraid I'm still seeing an issue.

Unless not live yet?

<img width="2010" height="1377" alt="Image" src="https://github.com/user-attachments/assets/af174b1e-908e-4c4a-8fb5-5df0bed3fdef" />
