### ISSUE TITLE
[bug] calibredb missing in latest container image causing metadata update timeouts

### ISSUE THREAD

**Issue by LogFelix** [crocodilestick/Calibre-Web-Automated#440]
### Description
I'm running the latest `crocodilestick/calibre-web-automated` image on a Raspberry Pi 4B (ARM64).  
Whenever I edit book metadata in the web UI, the application often hangs until I restart the container.

Upon investigation, I found that the `calibredb` command is missing inside the container.  
This likely explains why metadata updates fail or get stuck.

---

### Environment
- **Device:** Raspberry Pi 4B (4GB)
- **OS:** Raspberry Pi OS (64-bit)
- **Docker Compose Version:** v2.x
- **Image:** `crocodilestick/calibre-web-automated:latest`
- **Reverse Proxy:** Nginx (on the same Pi)
- **Library Size:** ~2.000 books

---

### Steps to Reproduce
1. Start the container using the provided docker-compose setup.
2. Enter the container:
   ```bash
   docker exec -it calibre-web-automated bash
   which calibredb
Observe that the command returns no result.

Edit any book metadata in Calibre-Web.

UI freezes until the container is restarted.

Expected Behavior
calibredb should be available in the container so that metadata updates are properly applied without manual container restarts.

Actual Behavior
calibredb is missing from the image.

Metadata updates cause UI timeouts.

Manual container restart is required to recover.

Logs
bash
Kopieren
Bearbeiten
/etc/s6-overlay/s6-rc.d/universal-calibre-setup/run: line 20: calibredb: command not found
Possible Fix
Include calibredb in the image by installing the Calibre CLI during the build process:

dockerfile
Kopieren
Bearbeiten
RUN apt-get update && apt-get install -y calibre
Alternatively, provide a separate utility container or script that handles metadata updates via calibredb.

This would ensure that metadata updates function as expected without requiring manual container restarts.

Additional Context
Verified on a fresh pull of crocodilestick/calibre-web-automated:latest (July 2025).

No other containers involved except nginx-proxy.

Same behavior persists across restarts.

yaml
Kopieren
Bearbeiten

**Comment by crocodilestick** [comment]
This has already been fixed in the dev container/ next release

**Comment by LogFelix** [comment]
okay great, thanks!

**Comment by LogFelix** [comment]
@crocodilestick I am still having this issue that calibre is crashing after metadata update and I have to restart docker. Afterwards the image is gone completely and I have to upload it from my computer locally
