### ISSUE TITLE
[Feature Request] Calibre feature - Embed metadata and embed comic metadata

### ISSUE THREAD

**Issue by Jojont54** [crocodilestick/Calibre-Web-Automated#483]
**Is your feature request related to a problem? Please describe.**
In my ereader no metadata are visible after SMB download.
Also to have a kosync aligned with webreader, the stored file should be aligned with the version download via OPDS or web ui download.

**Describe the solution you'd like**
Add a button in a book view to integrate metadata in the epub (must-have feature)
Same button for comics into the comicinfo.xml in the CBZ (nice to have feature)
(embed comics metadata also provide a CBR to CBZ converter, that could also be used for comic library) 

**Describe alternatives you've considered**
My current usage is a build of calibre in parallel of Calibre-web-automated to embed data through this 2 plugins

**Additional context**

<img width="70" height="58" alt="Image" src="https://github.com/user-attachments/assets/50632a88-264c-43fa-9b4a-86df735a5dcc" /> 

<img width="77" height="39" alt="Image" src="https://github.com/user-attachments/assets/61987d49-9676-46df-a79b-483f39b97dd0" />

**Comment by Jojont54** [comment]
<img width="279" height="327" alt="Image" src="https://github.com/user-attachments/assets/36a220ce-b306-4b71-93d9-e4329c44b4db" />

That how I image the feature could be.

embed comic metadata is a calibre plugin and is more a "nice to have" feature but not really as useful as epub metadata embedding because download currently doesn't embed metadata of metadata.opf in the comicinfo.xml, meaning there is no blocker for CBZ kosync without embed comic metadata plugin.

**Comment by crocodilestick** [comment]
Fixed in v4.0.3

**Comment by FlorianLaunay** [comment]
Hi @crocodilestick 

I run `v4.0.6` and metadata enforcement for CBZ/CBR format still does not work. Error log says the only formats supported are EPUB & AZW3:

```
[cover-metadata-enforcer]: No supported file formats found in /calibre-library/Akira Toriyama/Dragon Ball Perfect Edition - Tome 01 (211)/.
[cover-metadata-enforcer]: *** NOTICE **** Only EPUB & AZW3 formats are currently supported.
[cover-metadata-enforcer] Metadata for 'Dragon Ball Perfect Edition - Tome 01' not successfully enforced
[cover-metadata-enforcer] ERROR: Failed to enforce metadata for 'Dragon Ball Perfect Edition - Tome 01' (book_id=211): No supported files or enforcement failed
```

So what means your last message about a possible fix?
