### ISSUE TITLE
[bug] Fetch metadata (lubimyczytac.pl) doesn't display results

### ISSUE THREAD

**Issue by sltvtr** [crocodilestick/Calibre-Web-Automated#584]
**Describe the bug**
When I click on Fetch metadata and have selected only lubimyczytac.pl as provider there is nothing displayed but the search went fine acording to the logs.
As I observed - this happens when there is a "single" hit in search results. When there are two results in logs there is only one book displayed in Fetch metadata and so on...

**To Reproduce**
1. Go to Edit Book
2. Click on 'Fetch Metadata'
3. Leave only "lubimyczytac.pl" as provider
4. Enter example title "Polowanie na psy"
5. There are no results displayed

**Expected behavior**
There shoud be a book displayed.

**Screenshots**

<img width="885" height="842" alt="Image" src="https://github.com/user-attachments/assets/2989432b-5893-40ad-9d0a-c9da1b2ed7ac" />

<img width="1099" height="77" alt="Image" src="https://github.com/user-attachments/assets/09baf485-23c3-453a-a34a-f055b38f59fb" />

**Configuration(please complete the following information):**
 - OS: docker install 
 - Hardware: [x86 server]
 - Version [V3.1.4 ]

**logs**
[2025-08-29 16:14:53,715] DEBUG {urllib3.connectionpool:1049} Starting new HTTPS connection (1): lubimyczytac.pl:443
[2025-08-29 16:14:53,931] DEBUG {urllib3.connectionpool:544} https://lubimyczytac.pl:443 "GET /szukaj/ksiazki?phrase=Polowanie%20na%20psy HTTP/1.1" 200 20507
[2025-08-29 16:14:53,948] DEBUG {urllib3.connectionpool:1049} Starting new HTTPS connection (1): lubimyczytac.pl:443
[2025-08-29 16:14:54,312] DEBUG {urllib3.connectionpool:544} https://lubimyczytac.pl:443 "GET /ksiazka/5092568/polowanie-na-psy HTTP/1.1" 200 None

**Comment by sltvtr** [comment]
I have just checked different docker image: linuxserver/calibre-web and it seems that it all works fine there:

<img width="891" height="587" alt="Image" src="https://github.com/user-attachments/assets/ccf18db5-db02-4c52-8a65-d68bccee58dd" />

with the same debug info in logs:

```
[2025-09-05 08:29:04,966] DEBUG {connectionpool.py:1049} Starting new HTTPS connection (1): lubimyczytac.pl:443
[2025-09-05 08:29:05,471] DEBUG {connectionpool.py:544} https://lubimyczytac.pl:443 "GET /szukaj/ksiazki?phrase=Polowanie%20na%20psy HTTP/1.1" 200 18547
[2025-09-05 08:29:05,499] DEBUG {connectionpool.py:1049} Starting new HTTPS connection (1): lubimyczytac.pl:443
[2025-09-05 08:29:06,076] DEBUG {connectionpool.py:544} https://lubimyczytac.pl:443 "GET /ksiazka/5092568/polowanie-na-psy HTTP/1.1" 200 None
```

I have also compared file lubimyczytac.py from cps/metadata-provider directories of Yours image and from calibre-web and they look the same (beside different header comments).
So I think there may be a problem somewhere within calibre-web-automated.

**Comment by crocodilestick** [comment]
Fixed, will be in next dev build & next release <3

**Comment by sltvtr** [comment]
Hi,
I've manually included fix from Commit #55af1c5, but unfortunately I'm still facing the same issue.
I have also tried to use the :dev branch, same there.
Any ideas?

Best regards,
sltvtr

==edit==
I was checking this today, on version:  V3.1.4-DEV_BUILD-dev-160
The problem still persists.
