### ISSUE TITLE
[bug] Unable to get to the admin basic configuration page

### ISSUE THREAD

**Issue by kgladfelder** [crocodilestick/Calibre-Web-Automated#636]
**Describe the bug**
Unable to get to the admin basic configuration page

**To Reproduce**
1. Go to 'Admin'
2. Click on 'Basic Configuration'

**Expected behavior**
Basic Configuration page loads

**Screenshots**

**Configuration(please complete the following information):**
 - OS: `Debian`
 - Hardware: `AMD Ryzen 5 5600X based server`
 - Version: `V3.1.4-DEV_BUILD-dev-150`

**Additional context**

> Traceback (most recent call last):
> File "/lsiopy/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
> response = self.full_dispatch_request()
> File "/lsiopy/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
> rv = self.handle_user_exception(e)
> File "/lsiopy/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
> rv = self.dispatch_request()
> File "/lsiopy/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
> return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args) # type: ignore[no-any-return]
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
> File "/app/calibre-web-automated/cps/usermanagement.py", line 100, in decorated_view
> return login_required(func)(*args, **kwargs)
> ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
> File "/app/calibre-web-automated/cps/cw_login/utils.py", line 302, in decorated_view
> return current_app.ensure_sync(func)(*args, **kwargs)
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
> File "/app/calibre-web-automated/cps/admin.py", line 86, in inner
> return f(*args, **kwargs)
> File "/app/calibre-web-automated/cps/admin.py", line 284, in configuration
> return render_title_template("config_edit.html",
> config=config,
> provider=oauthblueprints,
> feature_support=feature_support,
> title=_("Basic Configuration"), page="config")
> File "/app/calibre-web-automated/cps/render_template.py", line 212, in render_title_template
> return render_template(instance=config.config_calibre_web_title, sidebar=sidebar, simple=simple,
> accept=config.config_upload_formats.split(','),
> *args, **kwargs)
> File "/lsiopy/lib/python3.13/site-packages/flask/templating.py", line 149, in render_template
> template = app.jinja_env.get_or_select_template(template_name_or_list)
> File "/lsiopy/lib/python3.13/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
> return self.get_template(template_name_or_list, parent, globals)
> ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/lsiopy/lib/python3.13/site-packages/jinja2/environment.py", line 1016, in get_template
> return self._load_template(name, globals)
> ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
> File "/lsiopy/lib/python3.13/site-packages/jinja2/environment.py", line 975, in _load_template
> template = self.loader.load(self, name, self.make_globals(globals))
> File "/lsiopy/lib/python3.13/site-packages/jinja2/loaders.py", line 138, in load
> code = environment.compile(source, name, filename)
> File "/lsiopy/lib/python3.13/site-packages/jinja2/environment.py", line 771, in compile
> self.handle_exception(source=source_hint)
> ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
> File "/lsiopy/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
> raise rewrite_traceback_stack(source=source)
> File "/app/calibre-web-automated/cps/templates/config_edit.html", line 5, in template
> <option value="0" {% if config.config_login_type == 0 %}selected{% endif %}>{{_('Use Standard Authentication')}}</option>
> ^^^^^^^^^^^^^^
> jinja2.exceptions.TemplateSyntaxError: expected token ',', got 'Use'

**Comment by Glennza1962** [comment]
Also, send to ereader (email) has disappeared

**Comment by tecosaur** [comment]
I think you may find this fixed in 5475cefa535c03e570dc7fafecc364d0c8556399

**Comment by kgladfelder** [comment]
That partially fixed it, after getting it set up and using groups for admin roles getting the following error:

```
Traceback (most recent call last):
File "/lsiopy/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
response = self.full_dispatch_request()
File "/lsiopy/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/lsiopy/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
rv = self.dispatch_request()
File "/lsiopy/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args) # type: ignore[no-any-return]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
File "/lsiopy/lib/python3.13/site-packages/flask_dance/consumer/oauth2.py", line 304, in authorized
token = self.session.fetch_token(
self.token_url,
...<2 lines>...
**self.token_url_params,
)
File "/lsiopy/lib/python3.13/site-packages/requests_oauthlib/oauth2_session.py", line 406, in fetch_token
self._client.parse_request_body_response(r.text, scope=self.scope)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/lsiopy/lib/python3.13/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 426, in parse_request_body_response
self.token = parse_token_response(body, scope=scope)
~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
File "/lsiopy/lib/python3.13/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 444, in parse_token_response
validate_token_parameters(params)
~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
File "/lsiopy/lib/python3.13/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 473, in validate_token_parameters
raise w
Warning: Scope has changed from "openid groups email profile" to "openid email profile".
```

**Comment by kgladfelder** [comment]
Was able to manually edit the `app.db` to remove `groups` from scope and working now.

**Comment by crocodilestick** [comment]
Fixed in v4.0.0
