### ISSUE TITLE
[bug] OIDC/OAUTH flakey with (presumably) expired token

### ISSUE THREAD

**Issue by bossanova808** [crocodilestick/Calibre-Web-Automated#663]
**Describe the bug**
Went to log in after some time away, used the 'Login with SSO' button.

Got an error about an 'invalid re-direct URI'..hit the button again and it logged me back in with this (not, I did not re-login, it was presumably just a token renewal thing):

<img width="2470" height="147" alt="Image" src="https://github.com/user-attachments/assets/e6d1cce5-a23b-441c-b760-8e8a1bcbe308" />

**Comment by crocodilestick** [comment]
Hey, I just pushed an update to dev that should hopefully fix this, I've also updated the docs in the OAuth wiki for the new fields ect. It'd be greatly appreciated if you could let me know if the problem is now fixed when you have the time :)

**Comment by bossanova808** [comment]
Hmm, I pulled it, then updated the setting with `auth.myhost.com` as per the docs, and now I get 'Not Found' from Authentik and I can't login (at - neither using the local address or via my CF tunnel..)

I'm stuck in a loop and can't get out!  Where is that setting stored so I can edit from outside?

**Comment by bossanova808** [comment]
Ok I found it - in at app.db, config - feels like it should be in with the other oauth settings under `oauthProvider` really - more logical spot.

I cleared the setting, restarted CWA and dang it I'm still stuck in the loop...hmmm...

**Comment by bossanova808** [comment]
Yep pretty stuck - every time I hit any CWA url I am immediately thrown to: 
`https://auth.mydomain.com/login?next=%2F` 

...with a big not found message

<img width="1322" height="1825" alt="Image" src="https://github.com/user-attachments/assets/693ff7be-0832-4605-aae4-506bee8b1e46" />

**Comment by bossanova808** [comment]
Ok, I am back to be able to log in (pulled again, or possibly it was some sort of dns/cache type issue??), and also cleared the setting in the sqllite DB.

I am back to seeing:

<img width="642" height="127" alt="Image" src="https://github.com/user-attachments/assets/5749c53b-d759-4ef4-9386-dad6cf09e5f8" />

So, the question now is - what to put in to the setting?  `auth.mydomain.com` results in the infinite loop 'not found' issue.  But that's what the docs imply for Authentik.

I am a little confused as to what this setting is really _actually_ doing - and therefore what it should be...

**Comment by crocodilestick** [comment]
Try the most recent dev build I just pushed, you shouldn't have any issues anymore and I've added a lot more info and examples to the wiki for help/ troubleshooting ect :)

**Comment by bossanova808** [comment]
Ok, so I changed it to books.mydomain.net as per the new instructions...

Saved and hit logout, immediately got:

```
500 Internal Server Error
The server encountered an internal error and was unable to complete your request. There is an error in the application.
Traceback (most recent call last):
File "/lsiopy/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
response = self.full_dispatch_request()
File "/lsiopy/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/lsiopy/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
rv = self.dispatch_request()
File "/lsiopy/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args) # type: ignore[no-any-return]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
File "/app/calibre-web-automated/cps/web.py", line 1519, in login
return render_login()
File "/app/calibre-web-automated/cps/web.py", line 1486, in render_login
redirect_count = session.get('_login_redirect_count', 0)
^^^^^^^
```

(I note that when I hit 'test metadata' this doesn't get automatically filled in).

In the docs, I would fit this case:
❌ Experiencing "invalid redirect URI" errors that resolve on retry

Thus I followed this guidance:
✅ Correct: https://cwa.example.com (your CWA instance)

...and that's the immediate resulting error.

(What I believe it _should_ be doing, really, is re-directing to Authentik for login...in an ideal flow, anyway.  But I understand that's not really implemented yet, so I guess it's trying to render the standard login at this point...the url is `https://books.mydomain.net/login?next=%2F`)

**Comment by crocodilestick** [comment]
Sorry that was on me, there were a couple silly errors in the last update. It should work as expected now, I just pushed a new dev image with the fix

**Comment by bossanova808** [comment]
Still not there I'm afraid - now I get to the Authentik login screen ok, login as normal, and then get an infinite reloading loop at `auth.mydomain.net`...

**Comment by bossanova808** [comment]
@crocodilestick Still experiencing the infinite loop with latest, pulled today.
