### ISSUE TITLE
Cannot send SMTP without authentication

### ISSUE THREAD

**Issue by mswdev** [crocodilestick/Calibre-Web-Automated#699]
**Describe the bug**
Seems that when I try to send SMTP that does not require authentication it still tries to send SMTP with simple authentication even though the fields are not filled out. My guess is the password is filled out still internally in the settings and cannot be removed?

I'm trying to send SMTP to a internal postfix-relay that does not require authentication or encryption as that is handled on the relay end.

I get this error when trying to do so `Smtplib Error sending e-mail: SMTP AUTH extension not supported by server.`

CWA attempts to connect to the relay but is immediately disconnected.

**To Reproduce**
Fill out SMTP without credentials and attempt to send a test email.

**Expected behavior**
Should successfully send SMTP.

**Screenshots**

<img width="1463" height="814" alt="Image" src="https://github.com/user-attachments/assets/bd9dbf84-f883-4a19-95b7-22a63fdd8003" />

**Configuration(please complete the following information):**
N/A

**Additional context**
N/A

**Comment by blackax1** [comment]
I can replicate on the latest dev docker image as well

**Comment by mitaka** [comment]
I can confirm that the error is present on the latest docker image from dockerhub.

**Comment by crocodilestick** [comment]
Fixed in v4.0.0

**Comment by mswdev** [comment]
@crocodilestick Unfortunately, it seems this issue is still occurring. I am getting the exact same error message on v4.05

**Comment by mswdev** [comment]
Opened a new bug report in #1141
