### ISSUE TITLE
[dev] [bug] Testing OIDC with Authentik. Working - but strange issues...

### ISSUE THREAD

**Issue by dierochade** [crocodilestick/Calibre-Web-Automated#715]
### Environment

I run the dev tag image on docker.  
I migrated from stock cw lately, if this is from interest.

---

### Issue Description

I can login wiht oidc, using authentik, but have two strange issues:

---

#### 1. Login Button Text

Although a custom Login Button text is saved in the dialogue and present after refresh, it is not rendered.  
Reads **"Log in with SSO"**.

---

#### 2. Admin Role Delegation

If I want to use the admin role delegation, there is a very strange behaviour:  
If I set

```
OAuth Scopes
openid profile email groups
```

I get a server 500 error with:

```
raceback (most recent call last):
File "/lsiopy/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
response = self.full_dispatch_request()
File "/lsiopy/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/lsiopy/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
rv = self.dispatch_request()
File "/lsiopy/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args) # type: ignore[no-any-return]
File "/lsiopy/lib/python3.13/site-packages/flask_dance/consumer/oauth2.py", line 304, in authorized
token = self.session.fetch_token(
self.token_url, ...<2 lines>... **self.token_url_params, )
File "/lsiopy/lib/python3.13/site-packages/requests_oauthlib/oauth2_session.py", line 406, in fetch_token
self._client.parse_request_body_response(r.text, scope=self.scope)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/lsiopy/lib/python3.13/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 426, in parse_request_body_response
self.token = parse_token_response(body, scope=scope)
~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
File "/lsiopy/lib/python3.13/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 444, in parse_token_response
validate_token_parameters(params)
~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
File "/lsiopy/lib/python3.13/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 473, in validate_token_parameters
raise w Warning: Scope has changed from "profile groups openid email" to "profile openid email".
```

---

### Token Example

This is although my jwt token includes:

```json
{
  "iss": "https://authentik.xxxx.de/application/o/calibre/",
  "sub": "91e13b306xxxxxxxxxxxxxx1dc4967bebf6e946eee10921a4c0a3b1cf6e63",
  "aud": "QP1xxd1sYsbXxxxxxxxxxxxxxxp32pikb3TkPWzP",
  "exp": 1761161619,
  "iat": 1761159819,
  "auth_time": 1761159819,
  "acr": "goauthentik.io/providers/oauth2/default",
  "ak_proxy": {
    "user_attributes": {
      "nextcloud_user_id": "Zib"
    },
    "is_superuser": true
  },
  "email": "zib@xxxx.de",
  "email_verified": true,
  "name": "Christoph",
  "given_name": "Christoph",
  "preferred_username": "zib",
  "nickname": "zib",
  "groups": [
    "authentik Admins",
    "Familie",
    "appadmins"
  ]
}
```

(With authentik provider settings `Include claims in id_token=true`)

---

### Additional Observation

More strange, I can use a a property mapping like this:

```python
return {
  "groups": [g.name for g in user.ak_groups.all()]
}
```

Then the token looks like:

```json
"groups": [
  "authentik Admins",
  "Familie",
  "appadmins",
  "authentik Admins",
  "Familie",
  "appadmins"
]
```

It doubles, ok. But the server error vanishes too!  
However, I am not granted admin role....

**Comment by dierochade** [comment]
@crocodilestick 

Cant confirm in my setup. 

Only issue #1 is fixed: Custom field name displayed
Issue #2 persists on V3.1.4-DEV_BUILD-dev-176 - Server error for me, seems completely identical as before

**Comment by crocodilestick** [comment]
Okay, I just pushed a new dev image (build 302) that should fix the OAuth once and for all, please let me know if it fixes things for you

**Comment by dierochade** [comment]
I run V3.2.0-DEV_BUILD-dev-302
Now it’s another error 500:

`Calibre-Web
500 Internal Server Error
The server encountered an internal error and was unable to complete your request. There is an error in the application.
Traceback (most recent call last):
File "/lsiopy/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
response = self.full_dispatch_request()
File "/lsiopy/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/lsiopy/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
rv = self.dispatch_request()
File "/lsiopy/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args) # type: ignore[no-any-return]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
File "/app/calibre-web-automated/cps/oauth_bb.py", line 127, in inner
return f(*args, **kwargs)
File "/app/calibre-web-automated/cps/oauth_bb.py", line 813, in generic_login
if not oauthblueprints[2]['blueprint'].session.authorized:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/lsiopy/lib/python3.13/site-packages/werkzeug/utils.py", line 107, in __get__
value = self.fget(obj) # type: ignore
File "/lsiopy/lib/python3.13/site-packages/flask_dance/consumer/oauth2.py", line 186, in session
ret = self.session_class(
client_id=self._client_id,
...<7 lines>...
**self.kwargs,
)
File "/app/calibre-web-automated/cps/oauth_bb.py", line 69, in __init__
super().__init__(*args, **kwargs)
~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
File "/lsiopy/lib/python3.13/site-packages/requests_oauthlib/oauth2_session.py", line 77, in __init__
super(OAuth2Session, self).__init__(**kwargs)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: Session.__init__() got an unexpected keyword argument 'blueprint'`

**Comment by claytono** [comment]
I'm seeing the same problem that @dierochade is with V3.2.0-DEV_BUILD-dev-303.

**Comment by smevawala** [comment]
I am seeing the same "blueprint" error as well

**Comment by marcosgarrido** [comment]
yes, me too.

**Comment by einstux** [comment]
Same blueprint error on V3.2.0-DEV_BUILD-dev-303

**Comment by h361758** [comment]
Just tried a clean deploy from scratch using the dev tag, and have the same blueprint issue.

I've tried updating oauth releated dependencies to latest, but didn't help.

**Comment by smevawala** [comment]
Any updates to this?  does oauth work for anyone on dev?

**Comment by kennyboy55** [comment]
Is there any update on this issue? I just updated to `V3.2.0-DEV_BUILD-dev-312`. The 'blueprint' error is still present for me. Details are in #758

**Comment by dierochade** [comment]
I tried the new V3.2.0-DEV_BUILD-dev-316

If there is the additional property mapping (as described in original post) in authentik

```
return {
  "groups": [g.name for g in user.ak_groups.all()]
}
```
it does work for me and gives me normal or admin role delegation as set in cwa "OAuth group for Admin" field.

However, if I do not the additional mapping, i again get the original internal server error:

```
Calibre-Web
500 Internal Server Error
The server encountered an internal error and was unable to complete your request. There is an error in the application.
Traceback (most recent call last):
File "/lsiopy/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
response = self.full_dispatch_request()
File "/lsiopy/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/lsiopy/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
rv = self.dispatch_request()
File "/lsiopy/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args) # type: ignore[no-any-return]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
File "/lsiopy/lib/python3.13/site-packages/flask_dance/consumer/oauth2.py", line 304, in authorized
token = self.session.fetch_token(
self.token_url,
...<2 lines>...
**self.token_url_params,
)
File "/lsiopy/lib/python3.13/site-packages/requests_oauthlib/oauth2_session.py", line 406, in fetch_token
self._client.parse_request_body_response(r.text, scope=self.scope)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/lsiopy/lib/python3.13/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 426, in parse_request_body_response
self.token = parse_token_response(body, scope=scope)
~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
File "/lsiopy/lib/python3.13/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 444, in parse_token_response
validate_token_parameters(params)
~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
File "/lsiopy/lib/python3.13/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 473, in validate_token_parameters
raise w
Warning: Scope has changed from "email openid groups profile" to "email openid profile"
```

This might be only a misconfiguration of settings? 

At the moment I do:
OAuth Scopes: 
email groups openid profile

**Comment by crocodilestick** [comment]
@dierochade Fixed.

The root cause was oauthlib being too strict—it treats any difference between the requested scopes and the returned scopes as a fatal error. When you removed the property mappings in Authentik, it returned a different scope set, causing the backend to crash.

I’ve patched the application to explicitly relax this check. You don't need to change any configuration on your end; just pull the latest image when the release goes out on Friday (or the dev image later this evening) and it will work automatically.

**Comment by kennyboy55** [comment]
I just pulled the latest dev (V3.2.0-DEV_BUILD-dev-317) and can confirm that logging in with OIDC is now possible. There does appear to be a redirect issue however. The steps I took:

- Logout of existing local account
- Click the `Login with ...` button
- I am correctly redirected to my identity provider
- After logging in I am redirected to https://calibre.domain.com/login/generic/authorized?code=<something>
- I am redirected back and forth (I think) between the identity provider and calibre-web-automated
- I get an ERR_TO_MANY_REDIRECTS in the browser
- After manually going back to the login page and clicking the login button again, it works and I am logged in.

Access log
```log
[2025-12-02 17:38:56] "GET /link/generic HTTP/1.1" 302 3461 0.005710
[2025-12-02 17:38:56] "GET /login/generic HTTP/1.1" 302 4293 0.006171
[2025-12-02 17:38:56] "GET /login/generic/authorized?code=15cf2ad953594...&state=Uwt7NHiId... HTTP/1.1" 302 3698 0.331158
[2025-12-02 17:38:56] "GET /login/generic/authorized HTTP/1.1" 302 3602 0.001520
[2025-12-02 17:38:56] "GET /login/generic HTTP/1.1" 302 4424 0.001596
[2025-12-02 17:38:56] "GET /login/generic/authorized?code=afc38e2c02...&state=QkYq7NyuLP... HTTP/1.1" 302 3697 0.332640
[2025-12-02 17:38:56] "GET /login/generic/authorized HTTP/1.1" 302 3601 0.003837
[2025-12-02 17:38:56] "GET /login/generic HTTP/1.1" 302 4424 0.003788
[2025-12-02 17:38:57] "GET /login/generic/authorized?code=e76e37fd7bc648f...&state=MoVP9aNCU4dFa... HTTP/1.1" 302 3700 0.337950
[2025-12-02 17:38:57] "GET /login/generic/authorized HTTP/1.1" 302 3604 0.002463
[2025-12-02 17:38:57] "GET /login/generic HTTP/1.1" 302 4427 0.003205
[2025-12-02 17:38:57] "GET /login/generic/authorized?code=7f243109bab44...&state=HU39qwyUoUdOJK... HTTP/1.1" 302 3697 0.322928
[2025-12-02 17:38:57] "GET /login/generic/authorized HTTP/1.1" 302 3601 0.002345
[2025-12-02 17:38:57] "GET /login/generic HTTP/1.1" 302 4423 0.004059
[2025-12-02 17:38:58] "GET /login/generic/authorized?code=9c8fe6663b684...&state=gsUdIUoH6i... HTTP/1.1" 302 3698 0.329312
[2025-12-02 17:38:59] "GET /login/generic/authorized?code=9c8fe6663b684d...&state=gsUdIUoH6i.. HTTP/1.1" 302 3602 0.006612
[2025-12-02 17:38:59] "GET /login/generic HTTP/1.1" 302 4425 0.005857
[2025-12-02 17:38:59] "GET /login/generic/authorized?code=65a71fa56112...&state=2EXANhIoiI2... HTTP/1.1" 302 3696 0.337492
[2025-12-02 17:38:59] "GET /login/generic/authorized HTTP/1.1" 302 3600 0.001922
[2025-12-02 17:38:59] "GET /login/generic HTTP/1.1" 302 4424 0.001742
[2025-12-02 17:39:00] "GET /login/generic/authorized?code=f42ceba2c5174bc...&state=MkqwQi1LzQb... HTTP/1.1" 302 3696 0.332381
[2025-12-02 17:39:00] "GET /login/generic/authorized HTTP/1.1" 302 3600 0.002588
[2025-12-02 17:39:00] "GET /login/generic HTTP/1.1" 302 4425 0.003829
[2025-12-02 17:39:00] "GET /login/generic/authorized?code=354e2a790afd458e8be...&state=a1yfy2eX68J2b... HTTP/1.1" 302 3697 0.328267
[2025-12-02 17:39:00] "GET /login/generic/authorized HTTP/1.1" 302 3601 0.002556
[2025-12-02 17:39:00] "GET /login/generic HTTP/1.1" 302 4425 0.003943
[2025-12-02 17:39:01] "GET /login/generic/authorized?code=b6a56314744e4a2...&state=6ndajsfNo... HTTP/1.1" 302 3698 0.351272
[2025-12-02 17:39:01] "GET /login/generic/authorized HTTP/1.1" 302 3602 0.002352
[2025-12-02 17:39:01] "GET /login/generic HTTP/1.1" 302 4425 0.003375
[2025-12-02 17:39:01] "GET /login/generic/authorized?code=2bc6ce7c64ac...&state=JVG8DKOl5... HTTP/1.1" 302 3692 0.334577
```

calibre-web.log
```log
[2025-12-02 17:39:00,407]  INFO {flask_dance.consumer.oauth2:279} state not found, redirecting user to login
[2025-12-02 17:39:00,414] DEBUG {cps.MyLoginManager:24} Session protection triggered for user unknown: identifier mismatch (stored: No
ne..., current: 9c7fc1810cc45f0d..., IP: ...)
[2025-12-02 17:39:00,539] DEBUG {cps.MyLoginManager:24} Session protection triggered for user unknown: identifier mismatch (stored: No
ne..., current: 9c7fc1810cc45f0d..., IP: ...)
[2025-12-02 17:39:00,864]  INFO {cps.oauth_bb:341} OAuth user '...' has admin role via group 'admin'
[2025-12-02 17:39:00,873] DEBUG {cps.MyLoginManager:24} Session protection triggered for user unknown: identifier mismatch (stored: No
ne..., current: 9c7fc1810cc45f0d..., IP: ...)
[2025-12-02 17:39:00,873]  INFO {flask_dance.consumer.oauth2:279} state not found, redirecting user to login
[2025-12-02 17:39:00,880] DEBUG {cps.MyLoginManager:24} Session protection triggered for user unknown: identifier mismatch (stored: No
ne..., current: 9c7fc1810cc45f0d..., IP: ...)
[2025-12-02 17:39:01,017] DEBUG {cps.MyLoginManager:24} Session protection triggered for user unknown: identifier mismatch (stored: No
ne..., current: 9c7fc1810cc45f0d..., IP: ...)
[2025-12-02 17:39:01,365]  INFO {cps.oauth_bb:341} OAuth user '...' has admin role via group 'admin'
[2025-12-02 17:39:01,373] DEBUG {cps.MyLoginManager:24} Session protection triggered for user unknown: identifier mismatch (stored: No
ne..., current: 9c7fc1810cc45f0d..., IP: ...)
[2025-12-02 17:39:01,374]  INFO {flask_dance.consumer.oauth2:279} state not found, redirecting user to login
[2025-12-02 17:39:01,381] DEBUG {cps.MyLoginManager:24} Session protection triggered for user unknown: identifier mismatch (stored: No
ne..., current: 9c7fc1810cc45f0d..., IP: ...)
[2025-12-02 17:39:01,507] DEBUG {cps.MyLoginManager:24} Session protection triggered for user unknown: identifier mismatch (stored: No
ne..., current: 9c7fc1810cc45f0d..., IP: ...)
[2025-12-02 17:39:01,839]  INFO {cps.oauth_bb:341} OAuth user '...' has admin role via group 'admin'

[2025-12-02 17:39:08,229]  INFO {cps.oauth_bb:341} OAuth user '...' has admin role via group 'admin'
[2025-12-02 17:39:08,241] DEBUG {cps.ub:72} Login and store session : 9c7fc1810cc45f0d0ce8c57ece42389ee3....
[2025-12-02 17:39:08,244] DEBUG {cps.oauth_bb:401} You are now logged in as: '...'
```

**Comment by dierochade** [comment]
> [@dierochade](https://github.com/dierochade) Fixed.

works for me (without quirk) now. Thank you for all your efforts!

**Comment by crocodilestick** [comment]
@kennyboy55 Confirmed bug. The session protection system was being too aggressive and clearing the OAuth "handshake" data because it thought the anonymous session was invalid.

I've pushed a fix that prevents session protection from triggering on anonymous users during the login flow. This should stop the redirect loop immediately. I have a couple things to add before building a new dev image but this will be in the dev-318 build that I'l release in a few hours

**Comment by kennyboy55** [comment]
I just pulled the latest version `V3.2.0-DEV_BUILD-dev-318`, sadly the issue persists. I checked the logs and I am seeing the exact same entries again. I tried in multiple browsers; clearing all site and cookie data; even checked if the committed changes are actually present in the image I pulled. I can't see a way to get it working :-(

Any ideas on what I can do or try from my side?

**Comment by kennyboy55** [comment]
Huh, I actually managed to get it working. In the configuration, I had my domain name filled in in the OAuth Redirect host:

<img width="777" height="131" alt="Image" src="https://github.com/user-attachments/assets/a5595198-0eb1-4fa7-9e96-cd624ec8997c" />

Once I removed that, it started working!

I was still experiencing some issue with the redirect loop, which was giving the errors below. I am quite certain that this is an issue on my side in the configuration of Authentik. It also showed a popup on the login screen, so I think that functionality is working as expected.
```log
[2025-12-03 18:53:22,858] ERROR {cps.oauth_bb:204} OAuth token expired during user info fetch: (token_expired) 
[2025-12-03 18:53:22,861] ERROR {cps.oauth_bb:388} OAuth provider generic returned empty user ID
[2025-12-03 18:53:22,880]  WARN {cps.web:1496} Authentication redirect loop detected from IP: 
[2025-12-03 18:53:26,050] ERROR {cps.oauth_bb:204} OAuth token expired during user info fetch: (token_expired) 
[2025-12-03 18:53:26,052] ERROR {cps.oauth_bb:388} OAuth provider generic returned empty user ID
[2025-12-03 18:53:31,343] ERROR {cps.oauth_bb:204} OAuth token expired during user info fetch: (token_expired) 
[2025-12-03 18:53:31,346] ERROR {cps.oauth_bb:388} OAuth provider generic returned empty user ID
[2025-12-03 18:53:36,289] ERROR {cps.oauth_bb:204} OAuth token expired during user info fetch: (token_expired) 
[2025-12-03 18:53:36,290] ERROR {cps.oauth_bb:388} OAuth provider generic returned empty user ID
[2025-12-03 18:53:46,812]  WARN {cps.web:1496} Authentication redirect loop detected from IP: 
[2025-12-03 18:53:48,509] ERROR {cps.oauth_bb:204} OAuth token expired during user info fetch: (token_expired) 
[2025-12-03 18:53:48,512] ERROR {cps.oauth_bb:388} OAuth provider generic returned empty user ID
```

Thank you so much for fixing it!

**Comment by dmitryikh** [comment]
With dev-318, I tried both `OAuth Redirect Host` empty and filled with my calibre address, but I still get too many redirects error.

**Comment by crocodilestick** [comment]
@dmitryikh I've pushed a final set of OAuth changes that should fix your set up, however if in dev-319 which will be released in a few hours your issues persist, I'm 99% sure there's a config error on your end. All the best!

**Comment by dmitryikh** [comment]
I tried the latest patch (dev-319), the error I'm getting:
```
[2025-12-04 13:57:33,384] ERROR {cps.oauth_bb:727} Unexpected error in generic OAuth login: 'NoneType' object has no attribute 'token'

[2025-12-04 15:00:19,520] ERROR {cps.oauth_bb:727} Unexpected error in generic OAuth login
Traceback (most recent call last):
  File "/app/calibre-web-automated/cps/oauth_bb.py", line 716, in generic_logged_in
    provider_user_id = register_user_from_generic_oauth(token)
  File "/app/calibre-web-automated/cps/oauth_bb.py", line 204, in register_user_from_generic_oauth
    resp = oauth_session.get(generic['oauth_userinfo_url'], verify=constants.OAUTH_SSL_STRICT)
  File "/lsiopy/lib/python3.13/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/app/calibre-web-automated/cps/oauth_bb.py", line 119, in request
    return super().request(method, url, *args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.13/site-packages/flask_dance/consumer/requests.py", line 191, in request
    self.load_token()
    ~~~~~~~~~~~~~~~^^
  File "/lsiopy/lib/python3.13/site-packages/flask_dance/consumer/requests.py", line 132, in load_token
    self._client.token = self.token
                         ^^^^^^^^^^
  File "/lsiopy/lib/python3.13/site-packages/werkzeug/utils.py", line 100, in __get__
    value = self.fget(obj)  # type: ignore
  File "/lsiopy/lib/python3.13/site-packages/flask_dance/consumer/requests.py", line 129, in token
    return self.blueprint.token
           ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'token'

```

**Comment by crocodilestick** [comment]
@dmitryikh please check dev-321 to see if you're still having this issue

**Comment by dmitryikh** [comment]
It used to work the day you fixed it. But now I'm getting:

```
[2025-12-07 13:56:23,584] ERROR {cps.oauth_bb:256} OAuth token expired during user info fetch: (token_expired) 
[2025-12-07 13:56:23,590] ERROR {cps.oauth_bb:440} OAuth provider generic returned empty user ID
[2025-12-07 13:56:26,914] ERROR {cps.oauth_bb:256} OAuth token expired during user info fetch: (token_expired) 
[2025-12-07 13:56:26,917] ERROR {cps.oauth_bb:440} OAuth provider generic returned empty user ID
[2025-12-07 13:56:26,943]  WARN {cps.web:1496} Authentication redirect loop detected from IP: *.*.*.*
```

I think the app can't renew the token and used the expired repeatedly.

I naively emptied the table `DELETE FROM flask_dance_oauth;` but it didn't help..

**Comment by Caligatio** [comment]
I just wanted to chime in that my Authentik setup is working without any issues. I'm happy to help you double check your Authentik settings.

**Comment by dmitryikh** [comment]
After I cleared the cookies all works fine! Thank you @crocodilestick and @Caligatio  for stepping in!

**Comment by Caligatio** [comment]
I just pulled the latest DEV image and am now hitting a redirect loop.  The logs say:

`ERROR {cps.oauth_bb:831} Unexpected error in generic OAuth login: ??? Unknown Error: None`

My browser eventually gives up and, if I then manually go to CWA, I get authorized (with error) successfully.

**Comment by andrew-manger** [comment]
I also have a redirect loop (am using PocketID). The error messages I am getting in the logs is:

`[2025-12-08 16:50:03,178] ERROR {cps.oauth_bb:817} Error in generic_logged_in: no exception for '1fXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXf7'`

The redacted string matches my sub from PocketID. 

If this is a separate issue, let me know and I can create a new one!

**Comment by dierochade** [comment]
Me too. However on dev 3.19 or 3.20 it seemed to work for everyone besides dmitryikh?

**Comment by crocodilestick** [comment]
I really hate OAuth 🙈🙈🙈🙈 @dierochade the issue was before that while generic OAuth was working for you guys, 3rd party Auth (Google & GitHub) was broken. Then 3rd party OAuth was fixed which broke Generic. Then yesterday I tried to fix it so they run in 2 separate flows so that both work but now Generic is still broken. I hate it so much 😂🙈

**Comment by Caligatio** [comment]
@crocodilestick If it helps, OIDC is the reason I switched from vanilla Calibre Web so your work is much appreciated. 

Sorry OIDC is a pain :(

**Comment by dmitryikh** [comment]
It's working like a charm with the latest fix in V3.2.0-DEV_BUILD-dev-329 .

Thank you all!

**Comment by crocodilestick** [comment]
@Caligatio I hope the newest build also fixes everything for you 🙏

**Comment by andrew-manger** [comment]
Glad to hear it's working for some of you! 

@crocodilestick However, I'm still having this issue:

Standard login and logout

```
[2025-12-09 16:41:02,947] DEBUG {cps.web:1668} You are now logged in as: 'andrew'
[2025-12-09 16:41:02,952] DEBUG {cps.ub:72} Login and store session : e91bf1cb6c2713936c956451e599d4fa3051d1c9fe21f3821d65f9c2a176ce5866f8ddf7fea0080bc01c0f09939702bfa52c30280923103f349fdf04febb34ab
[2025-12-09 16:41:12,606] DEBUG {cps.ub:84} Deleted session_key: e91bf1cb6c2713936c956451e599d4fa3051d1c9fe21f3821d65f9c2a176ce5866f8ddf7fea0080bc01c0f09939702bfa52c30280923103f349fdf04febb34ab
[2025-12-09 16:41:12,612] DEBUG {cps.web:1691} User logged out
```

OIDC attempted login
```
[2025-12-09 16:41:20,207]  INFO {cps.oauth_bb:395} OAuth user 'andrew' has admin role via group 'admin'
[2025-12-09 16:41:20,632]  INFO {flask_dance.consumer.oauth2:279} state not found, redirecting user to login

```

**Comment by Caligatio** [comment]
@crocodilestick I'm sadly seeing the same behavior as @andrew-manger which is the same behavior that caused me to open #819. I want to highlight that, after the failed login loop, I can browse back to CWA and log in successfully. I'm guessing some cookies are successfully set during the failed login such that a second attempt just works? 

Logs:
```
[2025-12-10 05:47:16,249]  INFO {cps.oauth_bb:395} OAuth user 'REDACTED_USERNAME' has admin role via group 'admin'
[2025-12-10 05:47:16,770]  INFO {flask_dance.consumer.oauth2:279} state not found, redirecting user to login
[2025-12-10 05:47:18,621]  INFO {cps.oauth_bb:395} OAuth user 'REDACTED_USERNAME' has admin role via group 'admin'
[2025-12-10 05:47:19,142]  INFO {flask_dance.consumer.oauth2:279} state not found, redirecting user to login
[2025-12-10 05:47:21,325]  INFO {cps.oauth_bb:395} OAuth user 'REDACTED_USERNAME' has admin role via group 'admin'
[2025-12-10 05:47:21,896]  INFO {flask_dance.consumer.oauth2:279} state not found, redirecting user to login
[2025-12-10 05:47:23,977]  INFO {cps.oauth_bb:395} OAuth user 'REDACTED_USERNAME' has admin role via group 'admin'
[2025-12-10 05:47:24,572]  INFO {flask_dance.consumer.oauth2:279} state not found, redirecting user to login
[2025-12-10 05:47:27,532]  INFO {cps.oauth_bb:395} OAuth user 'REDACTED_USERNAME' has admin role via group 'admin'
[2025-12-10 05:47:28,077]  INFO {flask_dance.consumer.oauth2:279} state not found, redirecting user to login


# This is then me browsing back to CWA, hitting login with OIDC, and successfully getting logged in
[2025-12-10 05:47:34,890]  INFO {cps.oauth_bb:395} OAuth user 'REDACTED_USERNAME' has admin role via group 'admin'
```

**Comment by kennyboy55** [comment]
I just updated from 319 to the latest dev. It was working perfectly 😅. I now get the error `Authentication loop detected. If you're experiencing login issues, please contact your administrator.` or `OAuth error: Provider returned invalid user information. Please try again.` I am unable to login at all now, and since I have disabled the old login form I am a bit stuck now. I took a quick look through the documentation, but can't find a url parameter I can pass to show the old login form again.

*edit, found the current version in the docker logs: V3.2.0-DEV_BUILD-dev-329

Log since starting container after update.
```log
[2025-12-10 14:35:48,687]  WARN {cps.config_sql:382} Log path  not valid, falling back to default
[2025-12-10 14:35:48,689]  INFO {cps:136} Enforcing SESSION_COOKIE_SECURE=True (OAuth enabled or HTTPS enforced)
[2025-12-10 14:35:48,732]  INFO {cps:197} Starting Calibre Web...
[2025-12-10 14:35:49,307]  WARN {py.warnings:110} /lsiopy/lib/python3.13/site-packages/flask_limiter/extension.py:324: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
  warnings.warn(

[2025-12-10 14:35:49,505]  INFO {apscheduler.scheduler:214} Scheduler started
[2025-12-10 14:35:49,505]  INFO {apscheduler.scheduler:1090} Added job "delete temp" to job store "default"
[2025-12-10 14:35:49,505]  INFO {apscheduler.scheduler:1090} Added job "end scheduled task" to job store "default"
[2025-12-10 14:35:49,507]  INFO {cps.tasks.thumbnail_migration:87} Thumbnail migration: No old subdirectories found, skipping migration
[2025-12-10 14:35:49,577]  INFO {apscheduler.scheduler:1090} Added job "immediately delete temp" to job store "default"
[2025-12-10 14:35:49,577]  INFO {apscheduler.executors.default:129} Running job "immediately delete temp (trigger: date[2025-12-10 14:35:49 CET], next run at: 2025-12-10 14:35:49 CET)" (scheduled at 2025-12-10 14:35:49.576973+01:00)
[2025-12-10 14:35:49,577]  INFO {apscheduler.scheduler:728} Removed job 2418b273709448868743d568b6a5aed1
[2025-12-10 14:35:49,584] DEBUG {cps.services.worker:80} Add Task for user: System - Clean up
[2025-12-10 14:35:49,584]  INFO {apscheduler.executors.default:156} Job "immediately delete temp (trigger: date[2025-12-10 14:35:49 CET], next run at: 2025-12-10 14:35:49 CET)" executed successfully
[2025-12-10 14:35:49,586] DEBUG {cps.tasks.clean:32} Deleted expired session_keys
[2025-12-10 14:35:50,143]  INFO {cps.ub:990} Updated generic OAuth provider from metadata URL
[2025-12-10 14:35:50,144]  INFO {cps.oauth_bb:610} Updated OAuth endpoints from metadata URL: https://authentik.domain.com/application/o/calibre-web/.well-known/openid-configuration
[2025-12-10 14:35:50,681]  INFO {cps.remotelogin:32} Magic Link QRCode is enabled
[2025-12-10 14:35:50,791]  INFO {cps.server:207} Starting Gevent server on [::]:8083
[2025-12-10 14:35:52,894] ERROR {cps.oauth_bb:258} OAuth token expired during user info fetch: (token_expired) 
[2025-12-10 14:35:52,895] ERROR {cps.oauth_bb:461} OAuth provider generic returned empty user ID
[2025-12-10 14:35:59,685] ERROR {cps.oauth_bb:258} OAuth token expired during user info fetch: (token_expired) 
[2025-12-10 14:35:59,685] ERROR {cps.oauth_bb:461} OAuth provider generic returned empty user ID
[2025-12-10 14:36:00,759] ERROR {cps.oauth_bb:258} OAuth token expired during user info fetch: (token_expired) 
[2025-12-10 14:36:00,759] ERROR {cps.oauth_bb:461} OAuth provider generic returned empty user ID
[2025-12-10 14:36:00,774]  WARN {cps.web:1501} Authentication redirect loop detected from IP: 192.168.1.1
[2025-12-10 14:36:01,665] ERROR {cps.oauth_bb:258} OAuth token expired during user info fetch: (token_expired) 
[2025-12-10 14:36:01,665] ERROR {cps.oauth_bb:461} OAuth provider generic returned empty user ID
[2025-12-10 14:36:19,310] ERROR {cps.oauth_bb:258} OAuth token expired during user info fetch: (token_expired) 
[2025-12-10 14:36:19,311] ERROR {cps.oauth_bb:461} OAuth provider generic returned empty user ID
```

Also some styling issues:

<img width="1289" height="75" alt="Image" src="https://github.com/user-attachments/assets/b41cc284-137f-4521-8aec-629aa33cf232" />

**Comment by kennyboy55** [comment]
I just tried reverting to the old DEV build in order to be able to login again, but couldn't get that to work. I pulled the latest DEV instead which is now `3.2.0-DEV_BUILD-dev-330`.

When clicking the "Login with Authentik" button, I immediatly get a 500 Internal Server error.

<img width="1405" height="550" alt="Image" src="https://github.com/user-attachments/assets/8f4317de-0a1d-4e23-8e78-b9dfaabfd403" />

```
Traceback (most recent call last):
File "/lsiopy/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
response = self.full_dispatch_request()
File "/lsiopy/lib/python3.13/site-packages/flask/app.py", line 920, in full_dispatch_request
return self.finalize_request(rv)
~~~~~~~~~~~~~~~~~~~~~^^^^
File "/lsiopy/lib/python3.13/site-packages/flask/app.py", line 939, in finalize_request
response = self.make_response(rv)
File "/lsiopy/lib/python3.13/site-packages/flask/app.py", line 1212, in make_response
raise TypeError(
...<3 lines>...
)
TypeError: The view function for 'oauth.generic_login' did not return a valid response. The function either returned None or ended without a return statement.
```

I am sorry that it is so difficult to get working, but I really appreciate all the effort you are putting in!

**Comment by Caligatio** [comment]
I noticed there was a commit, fb9d8e3299f7e45c127a539cc5872233a4775912, that mentioned fixing the redirect problem. Unfortunately it still persists but the error message has changed a bit:

```
[2025-12-12 05:53:46,564]  INFO {cps.oauth_bb:399} OAuth user 'REDACTED_USERNAME' has admin role via group 'admin'
[2025-12-12 05:53:46,594] ERROR {cps.oauth_bb:844} Unexpected error in generic OAuth login: ??? Unknown Error: None
[2025-12-12 05:53:46,602]  INFO {flask_dance.consumer.oauth2:279} state not found, redirecting user to login
[2025-12-12 05:53:47,044]  INFO {cps.oauth_bb:399} OAuth user 'REDACTED_USERNAME' has admin role via group 'admin'
[2025-12-12 05:53:47,100] ERROR {cps.oauth_bb:844} Unexpected error in generic OAuth login: ??? Unknown Error: None
[2025-12-12 05:53:47,109]  INFO {flask_dance.consumer.oauth2:279} state not found, redirecting user to login
[2025-12-12 05:53:47,571]  INFO {cps.oauth_bb:399} OAuth user 'REDACTED_USERNAME' has admin role via group 'admin'
[2025-12-12 05:53:47,619] ERROR {cps.oauth_bb:844} Unexpected error in generic OAuth login: ??? Unknown Error: None
[2025-12-12 05:53:47,628]  INFO {flask_dance.consumer.oauth2:279} state not found, redirecting user to login
[2025-12-12 05:53:48,099]  INFO {cps.oauth_bb:399} OAuth user 'REDACTED_USERNAME' has admin role via group 'admin'
[2025-12-12 05:53:48,154] ERROR {cps.oauth_bb:844} Unexpected error in generic OAuth login: ??? Unknown Error: None
[2025-12-12 05:53:48,162]  INFO {flask_dance.consumer.oauth2:279} state not found, redirecting user to login
[2025-12-12 05:53:48,872]  INFO {cps.oauth_bb:399} OAuth user 'REDACTED_USERNAME' has admin role via group 'admin'
[2025-12-12 05:53:48,906] ERROR {cps.oauth_bb:844} Unexpected error in generic OAuth login: ??? Unknown Error: None
```

**Comment by lordievader** [comment]
I'm seeing the same behavior as @Caligatio. Mainly the ` INFO {flask_dance.consumer.oauth2:279} state not found, redirecting user to login` seems troublesome. It redirects the browser in a loop until it gives up.

The loop occurs on the https://<calibre-web>/link/generic url. After letting it playout (and letting the browser give up) and browsing to https://<calibre-web> I'm logged in. Both the message that I'm logged in and "OAuth authentication failed due to an unexpected error. Please contact administrator." are shown in the bottom center (the two messages overlap).

**Comment by Caligatio** [comment]
@lordievader I'm pretty sure I fixed this with #827. If you know how to live edit a container, it's literally a one-word change.

**Comment by lordievader** [comment]
Live editing does not seem to do anything. The code does not seem te
reload? I'll look into it later to see of I can make a custom image with
the change for testing.

Op za 13 dec. 2025 05:39 schreef Brian Turek ***@***.***>:

**Comment by Caligatio** [comment]
@lordievader You need to edit the file and then manually restart the container. Restart keeps the container state so it won't recreate from the image.

**Comment by lordievader** [comment]
Ah yes. That makes things much easier. The fix indeed works 👌Thank you.

**Comment by kennyboy55** [comment]
I just pulled `V3.2.0-DEV_BUILD-dev-335` which contains #827 and everything seems to be working great now! Thanks so much!

**Comment by srvoets** [comment]
I am experiencing this issue, and updated my pull to latest, and calibre-web-automated:dev-402 but keep getting the same login loop:

`[2026-05-19 22:57:37,771]  WARN {cps.web:2162} Authentication redirect loop detected from IP: x.x.x.x
[2026-05-19 23:01:39,622]  WARN {cps.oauth_bb:1063} Fallback OAuth route '/link/generic' accessed - direct login may have failed
[2026-05-19 23:01:42,898]  INFO {cps.oauth_bb:440} OAuth user 'sean' has admin role via group 'calibre-web-admin'`

**Comment by tziuhtli** [comment]
> I am experiencing this issue, and updated my pull to latest, and calibre-web-automated:dev-402 but keep getting the same login loop:
> 
> `[2026-05-19 22:57:37,771] WARN {cps.web:2162} Authentication redirect loop detected from IP: x.x.x.x [2026-05-19 23:01:39,622] WARN {cps.oauth_bb:1063} Fallback OAuth route '/link/generic' accessed - direct login may have failed [2026-05-19 23:01:42,898] INFO {cps.oauth_bb:440} OAuth user 'sean' has admin role via group 'calibre-web-admin'`

I think your issue is not the same. I was experiencing the exact same as you. I am running under a reverse proxy (but only one). Fixed it by setting `TRUSTED_PROXY_COUNT: 1` (not sure why I had it equal to 2) in my docker compose.

**Comment by srvoets** [comment]
> > I am experiencing this issue, and updated my pull to latest, and calibre-web-automated:dev-402 but keep getting the same login loop:
> > `[2026-05-19 22:57:37,771] WARN {cps.web:2162} Authentication redirect loop detected from IP: x.x.x.x [2026-05-19 23:01:39,622] WARN {cps.oauth_bb:1063} Fallback OAuth route '/link/generic' accessed - direct login may have failed [2026-05-19 23:01:42,898] INFO {cps.oauth_bb:440} OAuth user 'sean' has admin role via group 'calibre-web-admin'`
> 
> I think your issue is not the same. I was experiencing the exact same as you. I am running under a reverse proxy (but only one). Fixed it by setting `TRUSTED_PROXY_COUNT: 1` (not sure why I had it equal to 2) in my docker compose.

I went ahead and put that into my docker config (unraid) but am having the same issue.

Is there a config file exposed somewhere I can edit cause right now im completely locked out.

Interestingly enough, I can login and display the homepage, but clicking anything else kicks me to the login screen
